add planning, tickets, timetracking, users
jeroenverh/teamleader-dotnet pull request #11
Opened 2018-02-01 08:09 UTC by lvermeulen

2018-02-01 08:20 UTC, lvermeulen commented
I see that the checks are failing because AppVeyor is using MSBuild v14.0 - switching to v15.0 (Visual Studio 2017) should solve the problem.

2018-02-02 21:18 UTC, jeroenverh commented
Fixed the build version issue, but there are some failing tests in the PR :)

2018-02-03 11:12 UTC, jeroenverh requested changes

2018-02-03 11:12 UTC, jeroenverh commented on src/TeamleaderDotNet/Common/Throttler.cs
>          // according to the teamleader documentation only 5 request per 25 seconds are allowed
Maybe also edit or remove this comment :)

2018-02-03 11:12 UTC, jeroenverh commented on src/TeamleaderDotNet.Tests/Planning/GetPlanningTest.cs
> +            int userId = Users.First(x => x.Email == "arne.moerman@orbitus.be").Id;
Might be better to use a fake email (like test@example.com instead of your real one? :) )

2018-02-03 11:12 UTC, jeroenverh commented on src/TeamleaderDotNet.Tests/Planning/GetPlanningTest.cs
> +            int userId = Users.First(x => x.Email == "jeroen.decuyper@orbitus.be").Id;
Same remark about the email :)

2018-02-03 11:12 UTC, jeroenverh commented on src/TeamleaderDotNet.Tests/TestBase.cs
> +    public abstract class TestBase
I think this is obsolete if we mock the TL api in the unit tests (loading a file to mimic the API)

2018-02-05 09:48 UTC, lvermeulen commented
I have addressed your comments in commit cc9a625

2018-02-05 14:30 UTC, merged